#!/bin/bash

# =========================[ CALC ]=========================
# | AUTHOR: mozzie                                         |
# | ---                                                    |
# | reverse polish notation calculator written in rust     |
# ==========================================================

PATH='/media/mozzie/Bulk600Gb2023-06-21/Projects/rpcalc/target/release/'
PROMPT='calc$  '

if [ ! -f "$PATH/rpcalc" ]; then
  echo "ERROR: could not locate rpcalc binary"
  exit 1
fi

cd "$PATH"

if [ ${#@} = 0 ]; then
  ANS='nil'
  DEF='nil'

  read -p "$PROMPT" EXPR

  while [ ! "$EXPR" = q ]; do

    if [[ "$EXPR" =~ ^"def ".* ]]; then
      DEF="${EXPR/def /}"
    else
      EXPR="${EXPR//fn/$DEF}"
      ANS=$(./rpcalc "${EXPR//ans/$ANS}")
      echo "=>  $ANS"
    fi

    read -p "$PROMPT" EXPR

  done
else
  echo "$(./rpcalc "$@")"
fi

exit 0
